node {
    try{
        docker.image('codeurjc/optsicom-compile').inside("-tu root") {
            stage('Clone Repository') {
                sh 'git clone -b refactor https://github.com/codeurjc/optsicom-framework.git'

                env.OPTSICOM_PATH = sh(script: 'echo ${PWD}/optsicom-framework', , returnStdout: true).trim()
            }

            stage('Compile Web') {
                dir("$OPTSICOM_PATH/optsicom-page/frontend") {
                    sh 'npm install'
                }

                dir("$OPTSICOM_PATH/optsicom-page/web"){
                    sh './compile.sh'
                }
            }
        }
    }finally{
        cleanWs()
    }
}	